# ===== Perfil PROD - MySQL 8 (RNF06) =====
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:condomanager}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Lisbon
spring.datasource.username=${DB_USER:condomanager}
spring.datasource.password=${DB_PASSWORD:condomanager}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
